Algoritmo "Exe_7"

Var

num1, num2, num3, num4 : inteiro
media : real


Inicio

escreval("Digite um numero: ")
  leia(num1)
escreval("Digite outro numero: ")
  leia(num2)
escreval("Digite outro numero: ")
  leia(num3)
escreval("Digite outro numero: ")
  leia(num4)
  
media <- (num1 + num2 + num3+ num4) / 4

escreva("A media dos numeros informados é: ", media)



Fimalgoritmo